# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hestSim <- function(nDataOut, N, reps, r, delta, MAXBAD, initData, params) {
    .Call('msdeTest_sdeEulerSim', PACKAGE = 'msdeTest', nDataOut, N, reps, r, delta, MAXBAD, initData, params)
}

.hestDrift <- function(xIn, thetaIn, nReps) {
    .Call('msdeTest_sdeDrift', PACKAGE = 'msdeTest', xIn, thetaIn, nReps)
}

.hestDiff <- function(xIn, thetaIn, nReps) {
    .Call('msdeTest_sdeDiff', PACKAGE = 'msdeTest', xIn, thetaIn, nReps)
}

.hestLoglik <- function(xIn, thetaIn, dT, nComp, nReps) {
    .Call('msdeTest_sdeLogLik', PACKAGE = 'msdeTest', xIn, thetaIn, dT, nComp, nReps)
}

.hestLogprior <- function(xIn, thetaIn, priorParams, priorType, nRv, nReps) {
    .Call('msdeTest_sdePrior', PACKAGE = 'msdeTest', xIn, thetaIn, priorParams, priorType, nRv, nReps)
}

.hestPost <- function(initParams, initData, dT, nDimsPerObs, fixedParams, nSamples, burn, nParamsOut, nDataOut, dataOutRow, dataOutCol, updateParams, updateData, priorType, priorParams, rwJumpSd, updateLogLik, nLogLikOut, updateLastMiss, nLastMissOut) {
    .Call('msdeTest_sdeEulerMCMC', PACKAGE = 'msdeTest', initParams, initData, dT, nDimsPerObs, fixedParams, nSamples, burn, nParamsOut, nDataOut, dataOutRow, dataOutCol, updateParams, updateData, priorType, priorParams, rwJumpSd, updateLogLik, nLogLikOut, updateLastMiss, nLastMissOut)
}

